export const allBanks = [
    { id: 'mnb', bank: 'Magyar Nemzeti Bank', status: true },
    { id: 'akcenta', bank: 'Akcenta' },
    { id: 'allianz', bank: 'Allianz Bank' },
    { id: 'banco', bank: 'Banco' },
    { id: 'bb', bank: 'Budapest Bank' },
    { id: 'b3takarek', bank: 'B3 Takarék Bank' },
    { id: 'cib', bank: 'CIB Bank' },
    { id: 'citybank', bank: 'Citibank' },
    { id: 'commerz', bank: 'Commerzbank' },
    { id: 'dtbank', bank: 'DT Bank' },
    { id: 'erste', bank: 'Erste Bank' },
    { id: 'evo', bank: 'EVO Bank' },
    { id: 'fhb', bank: 'FHB Bank' },
    { id: 'granit', bank: 'Granit Bank' },
    { id: 'hanwha', bank: 'Hanwha Bank' },
    { id: 'ing', bank: 'ING Bank' },
    { id: 'kdb', bank: 'KDB Bank' },
    { id: 'kh', bank: 'Kereskedelmi és Hitelbank' },
    { id: 'kinizsi', bank: 'Kinizsi Bank' },
    { id: 'magnet', bank: 'Magnet Bank' },
    { id: 'mfb', bank: 'Magyar Fejlesztési Bank' },
    { id: 'mkb', bank: 'Magyar Külkereskedelmi Bank' },
    { id: 'mtb', bank: 'MTB Bank' },
    { id: 'nhb', bank: 'NHB Bank' },
    { id: 'oberbank', bank: 'Oberbank' },
    { id: 'otp', bank: 'OTP Bank' },
    { id: 'polgari', bank: 'Polgári Bank' },
    { id: 'raiffeisen', bank: 'Raiffeisen Bank' },
    { id: 'sberbank', bank: 'Sberbank' },
    { id: 'sopron', bank: 'Sopron Bank' },
    { id: 'szechenyi', bank: 'Széchenyi Bank' },
    { id: 'unicredit', bank: 'UniCredit Bank' },
    { id: 'volksbank', bank: 'Volksbank' },
];
